# Generated by Django 2.2.3 on 2019-07-22 10:10

import uuid

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('colors', django.contrib.postgres.fields.ArrayField(
                    base_field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(default=0, validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(255)]), size=3), size=3)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
