# Generated by Django 2.2.3 on 2019-07-20 01:20

import django.contrib.postgres.fields
from django.db import migrations, models
import image.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0, validators=[image.models.validate_range]), size=3), size=3)),
                ('path', models.TextField(default='')),
            ],
        ),
    ]
