# Generated by Django 2.2.3 on 2019-07-19 17:46

import django.contrib.postgres.fields
from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='path',
        ),
        migrations.AlterField(
            model_name='image',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0, validators=[image.models.validate_range]), size=3), size=3),
        ),
    ]
