# Generated by Django 2.2.3 on 2019-07-24 11:26

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                                        django.core.validators.MaxValueValidator(255)]),
                size=3), default=None, null=True, size=3),
        ),
    ]
